/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as CommandPaletteRouteImport } from './routes/command-palette'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as FilesRouteImport } from './routes/files'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as MinimapRouteImport } from './routes/minimap'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandPaletteRoute = CommandPaletteRouteImport.update({
  id: '/command-palette',
  path: '/command-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimapRoute = MinimapRouteImport.update({
  id: '/minimap',
  path: '/minimap',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/awards': typeof AwardsRoute
  '/case-study': typeof CaseStudyRoute
  '/command-palette': typeof CommandPaletteRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/files': typeof FilesRoute
  '/invite': typeof InviteRoute
  '/minimap': typeof MinimapRoute
  '/plugins': typeof PluginsRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/awards': typeof AwardsRoute
  '/case-study': typeof CaseStudyRoute
  '/command-palette': typeof CommandPaletteRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/files': typeof FilesRoute
  '/invite': typeof InviteRoute
  '/minimap': typeof MinimapRoute
  '/plugins': typeof PluginsRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/awards': typeof AwardsRoute
  '/case-study': typeof CaseStudyRoute
  '/command-palette': typeof CommandPaletteRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/files': typeof FilesRoute
  '/invite': typeof InviteRoute
  '/minimap': typeof MinimapRoute
  '/plugins': typeof PluginsRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/awards'
    | '/case-study'
    | '/command-palette'
    | '/components'
    | '/contact'
    | '/design-system'
    | '/education'
    | '/experience'
    | '/files'
    | '/invite'
    | '/minimap'
    | '/plugins'
    | '/process'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/team'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/awards'
    | '/case-study'
    | '/command-palette'
    | '/components'
    | '/contact'
    | '/design-system'
    | '/education'
    | '/experience'
    | '/files'
    | '/invite'
    | '/minimap'
    | '/plugins'
    | '/process'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/team'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/awards'
    | '/case-study'
    | '/command-palette'
    | '/components'
    | '/contact'
    | '/design-system'
    | '/education'
    | '/experience'
    | '/files'
    | '/invite'
    | '/minimap'
    | '/plugins'
    | '/process'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/team'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AwardsRoute: typeof AwardsRoute
  CaseStudyRoute: typeof CaseStudyRoute
  CommandPaletteRoute: typeof CommandPaletteRoute
  ComponentsRoute: typeof ComponentsRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  FilesRoute: typeof FilesRoute
  InviteRoute: typeof InviteRoute
  MinimapRoute: typeof MinimapRoute
  PluginsRoute: typeof PluginsRoute
  ProcessRoute: typeof ProcessRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  SkillsRoute: typeof SkillsRoute
  TeamRoute: typeof TeamRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-palette': {
      id: '/command-palette'
      path: '/command-palette'
      fullPath: '/command-palette'
      preLoaderRoute: typeof CommandPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimap': {
      id: '/minimap'
      path: '/minimap'
      fullPath: '/minimap'
      preLoaderRoute: typeof MinimapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AwardsRoute: AwardsRoute,
  CaseStudyRoute: CaseStudyRoute,
  CommandPaletteRoute: CommandPaletteRoute,
  ComponentsRoute: ComponentsRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  FilesRoute: FilesRoute,
  InviteRoute: InviteRoute,
  MinimapRoute: MinimapRoute,
  PluginsRoute: PluginsRoute,
  ProcessRoute: ProcessRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  SkillsRoute: SkillsRoute,
  TeamRoute: TeamRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
